###
### Temporary duplicate entry point to test existing CI build
###
phases:
${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
  - template: eng/phases/pr-build.yaml
${{ if notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'PullRequest') }}:
  - template: eng/phases/full-build.yaml
